### ISSUE TITLE
Lock version of pytgcalls

### ISSUE THREAD

**Issue by MarshalX** [nitanmarcel/tl_radio#1]
https://github.com/nitanmarcel/tl_radio/blob/45ec4de2e47cab502b669cf6d5d3fa1e734c0830/requirements.txt#L5

A specific version should be set to avoid compatibility issues for future versions

**Comment by nitanmarcel** [comment]
https://github.com/nitanmarcel/tl_radio/commit/c282581f469c4450e02e938c27a420dbc4d82a9f
