### ISSUE TITLE
Exclude __pycache__ folders from git 

### ISSUE THREAD

**Issue by MarshalX** [nitanmarcel/tl_radio#2]

**Comment by nitanmarcel** [comment]
Yeah. I noticed this morning that I've missed the one from tl_radio/musicplayer.

Will be committed once I fix some small bugs in my function decorators.

**Comment by nitanmarcel** [comment]
https://github.com/nitanmarcel/tl_radio/commit/57f0778806f24aa979e7ee3401e77b943b55343d
